kind: Deployment
apiVersion: apps/v1
metadata:
  name: depl
  namespace: roll
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: depl-stra
  template:
    metadata:
      labels:
        app: depl-stra
    spec:
      containers:
        - name: apache
          image: ealen/echo-server
          ports:
            - containerPort: 80
