kind: Deployment
apiVersion: apps/v1
metadata:
  name: depl-g
  namespace: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
        - name: ui-green
          image: nginxdemos/hello
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: svc-g
  namespace: blue-green
spec:
  selector:
    app: green-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30070
  type: NodePort

