kind: Deployment
apiVersion: apps/v1
metadata:
  name: depl
  namespace: recreate
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: depl-stra
  template:
    metadata:
      labels:
        app: depl-stra
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80

