kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: meow
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-task
      labels: 
        app: batch-task
    spec:
      containers:
        - name: batch-cont
          image: busybox:latest
          command: ["sh", "-c", "echo Hello Kubernetes! && sleep 10"]
      restartPolicy: Never
