kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: meow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
