kind: Service
apiVersion: v1
metadata:
  name: flask-app-svc
  namespace: meow
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
