kind: Deployment
apiVersion: apps/v1
metadata:
  name: depl
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name: apache-pod
      labels:
        app: apache
    spec:
      containers:
        - name: apache-cont
          image: httpd:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
