kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: first-hpa
  namespace: apache
spec:
  scaleTargetRef:
    kind: Deployment
    name: depl
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
