kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: first-bind
  namespace: apache
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: apache-user
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: manager
